var _ictt=_ictt||[];"undefined"!==typeof ictigrp&&(_ictt.push(["_setIgrp",ictigrp]),"undefined"!==typeof ictdgrps&&_ictt.push(["_setDgrps",ictdgrps]),"undefined"!==typeof override&&_ictt.push(["_enableOverrideMode"]),_ictt.push(["_track"]));
if("undefined"==typeof __NASb){var __NASb=function(){};__NASb.prototype={_r:function(){this._ctt();for(var a=0;a<_ictt.length;a++)__NAS.push(_ictt[a])},_ctt:function(){/_track/.test(_ictt)||(this.hnr=!0)},_setPageTag:function(a){this.options.tags["p_"+a[0]]=a[1]},_setCustomVar:function(a){this.options.trackParams["c_"+a[0]]=a[1]},_setTrackingDomain:function(a){this.td=a},_setSegment:function(a){this.options.segment=a},_i:function(){this.options=
{};this.options.tags={};this.options.trackParams={};this.options.hrefParams=[];this.options.dn="";this.options.dgrps={};this.options.domain="";this.options.om=!1;this.options.segment=!1;this.protocol="https:"==document.location.protocol?"https://":"http://";this.td="ict.infinity-tracking.net";this.tg=[];this.cb=[];this.cbFired=!1;this.nv={};this.hnr=!1;this.ct=!0;this.ht=!1;return this},_enableGAIntegration:function(){__NAS.ct=
!1;var a,b,c=/_track/,d=setInterval(function(){if((a=__NAS._gc("__utma"))&&(b=__NAS._gc("__utmz")))__NAS._setCustomVar(["utma",a[0][1]]),__NAS._setCustomVar(["utmz",b[0][1]]),clearInterval(d),__NAS.set("utma",a[0][1]),__NAS.set("utmz",b[0][1]),__NAS.ct=!0,c.test(_ictt._ictt)&&__NAS._track()},100);setTimeout(function(){clearInterval(d);__NAS.ct=!0;c.test(_ictt._ictt)&&__NAS._track()},1E3)},_disableLand:function(){this.options.hrefParams.push("ictnoland=1")},_setTrackingDomain:function(a){this.td=
a},_gc:function(a){var b,c,d,e=document.cookie.split(";"),f=[];for(d=0;d<e.length;d++)b=e[d].substr(0,e[d].indexOf("=")),c=e[d].substr(e[d].indexOf("=")+1),b=b.replace(/^\s+|\s+$/g,""),RegExp(a).test(b)&&f.push([b,unescape(c)]);return 0<f.length?f:!1},_tagExternalLinks:function(a){var b=this;this._addCallback(function(){b._tagExternalElements("a","href",a)})},_tagExternalFormActions:function(a){var b=this;this._addCallback(function(){b._tagExternalElements("form","action",a)})},_tagExternalDestinations:function(a){this._tagExternalLinks(a);
this._tagExternalFormActions(a)},_tagExternalElements:function(a,b,c){var d,e,f;a=document.getElementsByTagName(a);for(var h=window.location.href.split("/"),h=h[0]+"//"+h[2],g=a.length-1;0<=g;g--)if(typeof a[g][b]!=__NAS.u&&-1===a[g][b].indexOf(h)&&!RegExp("ictd\\[master\\]|ictd\\[il"+this.options.igrp+"\\]","i").test(a[g][b])&&(d=a[g][b].split("/"))&&((e=d[0])&&(f=d[2]))&&(typeof c===__NAS.u||RegExp(c.join("|"),"i").test(e+"//"+f))){var j="?";-1!==a[g][b].indexOf(j)&&(j="&");var k=[],l,m;(l=this._gc("ictf_master"))&&
k.push("ictd[master]="+l[0][1]);(m=this._gc("ictf_il"+this.options.igrp))&&k.push("ictd[il"+this.options.igrp+"]="+m[0][1]);a[g][b]+=j+k.join("&")}},_autoPopulateInput:function(a){if(__NAS.hnr){if(a.id!=__NAS.u&&a.item!=__NAS.u){var b;if(b=document.getElementById(a.id))b.value=__NAS.get(a.item)}}else __NAS._addCallback(function(){__NAS._autoPopulateInput(a)})},_enableOverrideMode:function(){this.options.om=!0},_setIgrp:function(a){this.options.igrp=a},_setDgrp:function(a){this.options.dgrps[a[0]]=
a[1];this.options.dn=this.options.dn+a[0]+","},_setDgrps:function(a){for(var b in a)__NAS._setDgrp([b,a[b]])},_setDomain:function(a){this.options.domain=a},_d:function(a,b){var c=document.createElement("script");c.async=!0;c.type="text/javascript";c.src=this.protocol+this.td+a+this._gic()+"&ts="+this._c();"function"==typeof b&&(c.onload=b,c.onreadystatechange=function(){("complete"==this.readyState||"loaded"==this.readyState)&&b()});var d=document.getElementsByTagName("script")[0];
d.parentNode.insertBefore(c,d)},_gpt:function(){var a="",b;for(b in __NAS.options.tags)a+="&"+b+"="+__NAS._euc(__NAS.options.tags[b]);return a},_gtp:function(){var a="",b;for(b in __NAS.options.trackParams)a+="&"+b+"="+__NAS._euc(__NAS.options.trackParams[b]);return a},_ghp:function(){var a="?";/\?/.test(window.location)&&(a="&");return 0<__NAS.options.hrefParams.length?a+__NAS.options.hrefParams.join("&"):""},_gsp:function(){segmentTrackingParam=
"";__NAS.options.segment&&(segmentTrackingParam="&seg="+__NAS._euc(__NAS.options.segment));return segmentTrackingParam},_c:function(){return Math.round((new Date).getTime()/1E3)},_gdvsParam:function(){var a="";typeof document.webkitVisibilityState!==__NAS.u&&(a="&dvs="+__NAS._euc(document.webkitVisibilityState));return a},_gr:function(){var a=document.referrer,b=__NAS._gpm();b.utm_expid&&(a=b.utm_referrer||"");return __NAS._euc(a)},
_gpm:function(){var a={};if(window.location.search)for(var b=window.location.search.slice(1).split("&"),c=0;c<b.length;c++){var d=b[c].split("=");a[d[0]]=decodeURIComponent(d[1])}return a},_track:function(){var a="",b="";!0==__NAS.options.om&&(a="&dgrps="+__NAS._euc(__NAS.options.dn));""!=__NAS.options.domain&&(b="&domain="+__NAS._euc(__NAS.options.domain));__NAS.ct&&(!__NAS.ht&&!document.webkitHidden)&&(a="/track?igrp="+__NAS._euc(__NAS.options.igrp)+
a+b+"&vref="+__NAS._gr()+"&href="+__NAS._euc(window.location+__NAS._ghp())+__NAS._gpt()+__NAS._gtp()+__NAS._gsp()+"&res="+__NAS._euc(screen.width+"x"+screen.height)+"&t="+__NAS._euc(document.title)+__NAS._gdvsParam()+"&ua="+__NAS._euc(__NAS._guah()),__NAS._d(a),__NAS.ht=!0);document.addEventListener&&document.addEventListener("webkitvisibilitychange",function(){__NAS._handleVisibilityChange()},
!1)},_handleVisibilityChange:function(){"visible"==document.webkitVisibilityState&&__NAS._track()},_p:function(){var a;if(this.tg[0])for(a in this.tg){var b="/trig?igrp="+__NAS._euc(__NAS.options.igrp)+__NAS._gsp()+"&vref="+__NAS._gr();a=this.tg[a];var b=b+("&act="+a.action),c=0;for(c in a.dt)b+="&"+__NAS._euc(c)+"="+__NAS._euc(a.dt[c]);return b}},_guah:function(){var a;a=unescape(__NAS._euc(navigator.userAgent));
var b=1,c=0,d;if(a){b=0;for(d=a.length-1;0<=d;d--)c=a.charCodeAt(d),b=(b<<6&268435455)+c+(c<<14),c=b&266338304,b=0!=c?b^c>>21:b}return b},_addCallback:function(a){"function"==typeof a&&(this.cb.push(a),this.cbFired&&a.apply());return this},_fcb:function(){if(__NAS.hnr){this.cbFired=!0;for(var a in __NAS.cb)if(__NAS.cb.hasOwnProperty(a)&&"function"==typeof __NAS.cb[a])__NAS.cb[a]()}},page:function(a,b){"function"!=typeof b&&(b=
!1);this.trig("page",{href:this.protocol+window.location.host+a},b)},_pageView:function(a,b){return __NAS.page(a,b)},trig:function(a,b,c){"function"!=typeof c&&(c=!1);this.tg=[];var d=new NAST;d.action=a;d.dt=b;this.tg.push(d);this._d(this._p(),c)},_customTrigger:function(a,b,c){return __NAS.trig(a,b,c)},set:function(a,b){this.nv[a]=b},_set:function(a,b){return __NAS.set(a,b)},get:function(a){return typeof __NAS.nv[a]!=__NAS.u?__NAS.nv[a]:
!1},_get:function(a){return __NAS.get(a)},storeItem:function(a,b){var c=new Date;c.setFullYear(c.getFullYear()+10);document.cookie="ictf_"+__NAS._euc(a)+"="+__NAS._euc(b)+"; path=/;expires="+c.toGMTString()+";";return!0},retrieveItem:function(a){var b;return(b=this._gc("ictf_"+__NAS._euc(a)))&&typeof b[0][1]!=__NAS.u?b[0][1]:!1},removeItem:function(a){var b=this.retrieveItem(a);document.cookie="ictf_"+__NAS._euc(a)+"=; expires="+(new Date).toGMTString()+"; path=/;";
return b},_gic:function(){var a,b,c="";if(a=this._gc("ictf_"))for(var d=0;d<a.length;d++)b=a[d][0],b=b.replace(/^ictf_/g,""),c+="&d["+__NAS._euc(b)+"]="+__NAS._euc(a[d][1]);return c},_ge:function(a){var b=[],c=document.getElementsByTagName("*"),d=c.length;a=RegExp("(^|\\s)"+a+"(\\s|$)");for(var e=0,f=0;e<d;e++)a.test(c[e].className)&&(b[f]=c[e],f++);return b},_dr:function(a,b){for(var c=ictnumbers[b],d=0;d<a.length;d++)if(typeof c!=
__NAS.u&&"client"!=c){var e,f;for(f in e=__NAS._ge(a[d]))__NAS._dri(e[f],c)||(e[f].innerHTML=c)}},_dri:function(a,b){return/(^|\s)clickable(\s|$)/.test(a.className)?(a.innerHTML='<a href="tel:'+b.replace(/\s/g,"")+'">'+b+"</a>",!0):!1},push:function(a){if("object"==typeof a){argument=[];for(var b in a)argument[b]=a[b];a=argument.shift();if(typeof this[a]!=__NAS.u)return this[a].apply(this,argument)}else if(typeof this[a]!=__NAS.u)return this[a].apply()},
_rnr:function(){if(typeof ictnumbers!=__NAS.u)for(var a in __NAS.options.dgrps)__NAS._dr(__NAS.options.dgrps[a],a);return this},_ictcc:function(){__NAS.hnr=!0;typeof ictvid!=__NAS.u&&__NAS.set("ictvid",ictvid);if(typeof ictnumbers!=__NAS.u)for(var a in __NAS.options.dgrps)__NAS.set("ictnumbers_"+a,ictnumbers[a]);__NAS._rnr()._fcb()},_euc:encodeURIComponent};__NASb.prototype.u="undefined";var NAST=function NAST(){NAST.action=null;NAST.dt=
null};NAST.prototype={};var ictcc=function(){__NAS._ictcc()},__NAS=new __NASb;__NAS._i()._r();"undefined"!=typeof _ictt&&(window.attachEvent?window.attachEvent("onload",function(){__NAS._rnr()._fcb()}):window.addEventListener?window.addEventListener("load",function(){__NAS._rnr()._fcb()},!1):document.addEventListener("load",function(){__NAS._rnr()._fcb()},!1));__NAS._ictt=_ictt;_ictt=__NAS};
